### PR TITLE
New Field : Date Picker 

### PR DESCRIPTION
**Pull request by devariya**
Just add new date picker field based on jquery ui datepicker  :smile:

### CODE REVIEW

**Comment by Theme20** [comment]
Thanks man.

**Comment by devariya** [comment]
You are welcome :smiley:  when you will merge this ?

**Comment by Codestar** [comment]
Hey bro, thanks for contribute, i will merge it in v1.1 :wink:

**Comment by devariya** [comment]
Could you please add it soon .

**Comment by Codestar** [comment]
Yes coming soon :)

**Comment by devariya** [comment]
Also don't forget about time filed .

**Comment by Codestar** [comment]
Yes, Actually i am working on a new theme now, and i am planing to add more fields on framework. time picker, date picker, js css editor, button group etc... I have not free-time now. but it will be ready soon :wink:

**Comment by devariya** [comment]
Thanks , same here .

**Pull request closed without merging**
