### PR TITLE
Group Field : Added Specific ID and Class name!

### PR DESCRIPTION
**Pull request by Ansif**
Added Specific ID for each group accordion! And added specific class for group remove button!

### CODE REVIEW

**Comment by Codestar** [comment]
Great :+1:  thanks for contribute.

**Comment by Codestar** [comment]
Btw, some improves about classname. Specific classname added. btw, i used field-title for classname. because group field-title is not static. it is changing always when you change field title. but group title is static always. Sorry for my bad english :smile: you will understand it when check code LOL :smile: 

https://github.com/Codestar/codestar-framework/commit/5547eee4339215e2b6b8a8f21df771e5d68e3ea9

**Comment by Ansif** [comment]
Hi,

Yes, i understand about group title is not static. But i added that for hiding title input field & remove button from my css! Users not able to change that title name. That's what i want! A default preloaded accordion sets. 😉 

Thanks! 👍

**Comment by Codestar** [comment]
Great, Cheers :+1:

**Pull request merged**
