### PR TITLE
Add FAQ : "How to create cutomizer live preview"

### PR DESCRIPTION
**Pull request by ariona**
I have added a sample for create Customizer live preview to the github-pages on how-to section.

### CODE REVIEW

**Comment by doukali** [comment]
hey ariona can u explain how can i use multiselect in categories type in the loop to get post i mean i choose the cats from the theme option panel ana in  index it show the posts in ?

**Comment by ariona** [comment]
Hi @doukali , I think you could do that by passing category parameter in get_posts/query function before the loop start. more info can be read https://codex.wordpress.org/Template_Tags/get_posts

You can pass multiple category by separating its category ids using commas.

**Comment by Codestar** [comment]
Hi, Thanks for contribute bro, It is great :+1: :100:

**Comment by ariona** [comment]
Haha, just dont merge that part, I don't really familiar with the site structure, and i just wanna test it on my own github page, but it still didn't work. 😂

**Comment by Codestar** [comment]
haha, i need to merge it, because respect to your effort :smile: hahaha

**Comment by ariona** [comment]
haha then you should readd it again, and I think you should reedit the title again to "How to __create__ ...", i missed the create word 😂

**Comment by Codestar** [comment]
Oh yes, i fixed it now :smile:

**Pull request merged**
