### PR TITLE
Include cs-framework with get_template_part()

### PR DESCRIPTION
**Pull request by mrinal013**
When a theme is checking with Theme Check plugin, using require_once() in theme functions file results a notice -

INFO: inc/introduce-functions.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.

### CODE REVIEW

**Comment by mrinal013** [comment]
Codestar framework include for WordPress Theme Directory standard

**Comment by NoahjChampion** [comment]
Hi. I understand what you're saying (and I could be corrected) but I think you have this function and cs-framework mixed up a little bit. See above reference link. 

Reference: @ [get_template_part();](https://developer.wordpress.org/reference/functions/get_template_part/)
```php
get_template_part();
```

This is for calling php template files that render an HTML output (typically) on the frontend of your website. 

Example: In `single.php` you may want to load a separate php file inside of your `single.php`. To do that you would use `get_template_part();` like so...

`get_template_part('templates/special-content');`

This would then load 

```php
your-domain.com/wp-content/themes/your-theme/templates/special-content.php
```

inside of your `single.php` content.

A quick example would be...

```php
<?php
/**
 * The template for displaying pages.
 */

get_header(); ?>

	<div id="primary" class="site-content">
		<div id="content" role="main">

				<?php get_template_part( 'templates/page' );
				  // Loads content from /your-theme/templates/page.php
				?>

		</div><!-- #content -->
	</div><!-- #primary -->

<?php get_sidebar(); ?>
<?php get_footer(); ?>
```

This is what Theme Check plugin is referring to when it says

> separate sections of a template

Codestar doesn't load any "template" related files, only framework options to configure different settings in the backend. 

I'm not sure if you are running a `require();` or an `include();` from your `introduce-functions.php` file but if you are for template files then this would probably be why the notice came up. 

If you are not, then there is another issue as to why Theme Check is triggering this issue that we may have to take a look at. But again, this is just a "Notice" message. It may or may not apply may or may not need to be changed. 

I'm guessing you changed this function and the Notice message went away? Please confirm. :)

If it did then Theme Check will probably have this issue/notice message because it is not detecting whether your theme is using a Framework or not. It may only be checking for themes based on themes from scratch, in which `require();` or `include();` may **only** be in the top level functions.php of a theme instead of a subfolder file like a framework, for instance. 

Let me know. Thanks!

**Comment by mrinal013** [comment]
Hi @NoahjChampion 

I tried to include cs-framework.php within introduce-functions.php by following ways:
include() and include_once()
require() and require_once()
every time it results same INFO notice. However, it is just a notice, it will not a big deal for theme submission.

Although, [get_template_part()](https://developer.wordpress.org/reference/functions/get_template_part/
) is generally used for template file include in another file. But, it can also used for any kind of file.

> Makes it easy for a theme to reuse sections of code in a easy to overload way for child themes.

Thanks

**Comment by NoahjChampion** [comment]
Hi @mrinal013 

Ok. Well it's up to @Codestar when he gets time to check it out. Thanks. 

Good luck with your theme! Make sure notify the git when it is in the Repo! :) Cheers!

**Comment by mrinal013** [comment]
Hi @NoahjChampion 

I tested it again by include_once() in functions.php rather than introduce-functions.php. It does not give INFO notice. This notice shown when it used in another file of theme.
At end, I think its better to clear that, codestar must include in functions.php

Thanks

**Pull request closed without merging**
