### PR TITLE
Added OR Condition In DEPENDENCY

### PR DESCRIPTION
**Pull request by technofreaky**
Now users can have OR condition with field Dependency 

Here is a sample code
```php
array(
  'name'    => 'footer',
  'title'   => __('Footer Section','booss'),
  'icon'    => 'fa fa-code-fork',
  'fields'  => array(
        array(
            'id' => 'footer_left_side',
            'type' => 'select',
            'title' => __("Left Side",'booss'),
            'options' => array("option1" => 'Option1',"option2" => 'option2'),
        ),
        array(
            'id' => 'footer_right_side',
            'type' => 'select',
            'title' => __("Left Side",'booss'),
            'options' => array("option1" => 'Option1',"option2" => 'option2'),
        ),
        
        array(
            'id' => 'footer_side',
            'type' => 'text',
            'title' => __("Main Text",'booss'),
            'dependency'   => array( 'footer_right_side|footer_left_side', 'OR|OR', 'option1|option2' ),
        )
  ),
)
`

### CODE REVIEW

**Comment by samjco** [comment]
Awesome!

**Comment by technofreaky** [comment]
@samjco 

dependency already exists in codestar. but allowed conditions are like (== , != , any ) you can't use OR in the condition field. so i modified the code to allow or condition. 

OR condition can be called in the same way like other conditions.

== Condition
` 'dependency'   => array( 'dep_15', '==', 'world' ), `

OR Condition
`'dependency'   => array( 'dep_15', 'OR', 'world' ),`

**Comment by Codestar** [comment]
Thanks for contribute @technofreaky also can you leave an message via routewp[at]gmail[dot]com about framework v2

**Comment by technofreaky** [comment]
@Codestar  thanks. but is that your email id or ? i dint get you ?

are u working on any new version ?

**Comment by Codestar** [comment]
No problem bro, i will explain it via email.

**Comment by technofreaky** [comment]
@Codestar i have sent an email :)

**Comment by Codestar** [comment]
Nice ;) I've reply. :+1:

**Pull request merged**
