### PR TITLE
Sticky Header for Options Framework

### PR DESCRIPTION
**Pull request by OmarAtta**
sticky

### CODE REVIEW

**Comment by NoahjChampion** [comment]
👍

**Comment by DeathMark** [comment]
Your code is awesome but it doesn't update header width while browser is resizing. I think you should add the below code to made this feature work perfectly. 
```
$(window).on('resize.amy-sticky-header', function() {
	if ($(this).scrollTop() > headerOffset - 32) {
		var headerWidth	= header.siblings('.amy-body').outerWidth();

		header.css('width', headerWidth);
	}
});
```

**Comment by OmarAtta** [comment]
@DeathMark , Thanks for contribute, I updated the code.

**Comment by efirvida** [comment]
didn't work for me, so I make my own code:

css
``` CSS
.cs-header.sticky {
    position    : fixed;
    margin-top  : 0;
    top         : 32px;
    z-index     : 9999;
    box-sizing  : border-box;
    background: #efc47D;
    transition: all 0.4s ease;
}
```
js
   ``` JS
 $.fn.CSFRAMEWORK_STICKYHEADER = function () {
        if (this.length) {
            $(window).on('scroll.csStickyHeader', function () {
                if ($(this).scrollTop() > 1) {
                    $('.cs-header').addClass("sticky").css('width', $('.cs-body').width());
                }
                else {
                    $('.cs-header').removeClass("sticky").css('width','auto');
                }
            });
        }
    };
```

**Pull request closed without merging**
