### PR TITLE
Adding Post Type List Support!

### PR DESCRIPTION
**Pull request by Ansif**
Get a list of post types!

### CODE REVIEW

**Comment by NoahjChampion** [comment]
Usage?

**Comment by Ansif** [comment]
We can use it as our Post listing widget.

custom-widget

👍

**Comment by NoahjChampion** [comment]
:) I know that. I mean in the config? Example?

**Comment by Ansif** [comment]
I used code from #51!

And added that particular post type field by using following code : 
`// Post Type
$post_type_value = esc_attr( $instance['post_type'] );
$post_type_field = array(
	'id'    => $this->get_field_name('post_type'),
	'name'  => $this->get_field_name('post_type'),
	'type' => 'select',
	'options' => 'post_types',
	'default_option' => __( 'Select Post Type', 'text_domain' ),
	'title' => __( 'Post Type :', 'text_domain' ),
);
echo cs_add_element( $post_type_field, $post_type_value );`

I hope you mean that! 👍

**Comment by NoahjChampion** [comment]
Yes. Thanks! Easy enough.

**Comment by Codestar** [comment]
Yes it is great. Thanks for contribute :+1:  :wine_glass:

**Comment by NoahjChampion** [comment]
@Ansif 

Thanks for this. I just used it :) My theme is almost done and beautiful and easy to use because of @Codestar's easy framework. <3 It's almost marketplace war time #Salute

**Comment by Codestar** [comment]
Nice :+1: @NoahjChampion We will wait your theme release =)

**Comment by Ansif** [comment]
@NoahjChampion, Glad you liked and used it! 👍 

Me also waiting for your new theme! Will be hit, 💯% success!

**Pull request merged**
