### PR TITLE
Added cleaner cs select styles

### PR DESCRIPTION
**Pull request by NoahjChampion**
Added cleaner cs selects styles. 

See screenshots. 

- Added cs-pseudo-field-last to even teh spacing for background types.
- @ http://take.ms/rXSwE

- Normal select styles
- @ http://take.ms/2Ai4Q

### CODE REVIEW

**Comment by NoahjChampion** [comment]
@Codestar I just saw this conflicts with Typography type class chosen. 

Do you see a small tweak to fix it?

**Comment by Codestar** [comment]
@NoahjChampion it is looking good really, but this is a personal thing. as you know, i am trying to stay for "a lightweight framework" always. you can use this custom modification as personally. Let's avoid conflict and use default selectors.

**Comment by NoahjChampion** [comment]
@Codestar 

Ok. Sounds good. Yes, I only notice the conflict after pull request. I will just create a new field `select_clean` so I can use chosen, select or clean select. Maybe someone else might want to use, so it will be there without conflict. 

Thanks.

**Comment by Codestar** [comment]
@NoahjChampion yes, `select_clean` new field sounds good :+1: nice idea. yes we can add it.

**Comment by NoahjChampion** [comment]
"we"?

> yes we can add it.

So do a pull request?

**Comment by Codestar** [comment]
I mean, yes i can add this `select_clean` new field future...

**Comment by NoahjChampion** [comment]
Ok. 

There is some extra css that can be removed. The extra css is for the javascript - when select is disabled.  But I didn't use it the javascript because I couldn't get it to work. But I don't know Javascript :)

See what I mean @ http://red-team-design.com/making-html-dropdowns-not-suck/

Javascript can give disabled select look...

image

You can keep it or throw it away. You will know why it is.

**Comment by NoahjChampion** [comment]
It will be lighter without Javascript I think and removing the extra css. 

Better, thoughts?

**Pull request closed without merging**
