### PR TITLE
Added Support for WP Nav Menus!

### PR DESCRIPTION
**Pull request by Ansif**
```php
array(
  'id'         => 'choose_menu',
  'type'       => 'select',
  'title'      => __( 'Choose Menu', 'cs-framework' ),
  'info'      => __( 'Choose custom menus for this page.', 'cs-framework' ),
  'options'    => 'menus',
  'default_option' => __('Select your menu', 'cs-framework'),
),
```

### CODE REVIEW

**Comment by Codestar** [comment]
Yes, it is nice :+1: Thanks for added.

**Comment by Codestar** [comment]
Btw, i improved it a little. take a look. [options.class.php#L294](https://github.com/Codestar/codestar-framework/blob/master/classes/options.class.php#L294)

Now using  [wp_get_nav_menus](https://developer.wordpress.org/reference/functions/wp_get_nav_menus/) adnd you can use all get_terms args https://developer.wordpress.org/reference/functions/get_terms/ in query_args param.

```php
array(
  'id'             => 'unique_select_10_1',
  'type'           => 'select',
  'title'          => 'Select with Menus',
  'options'        => 'menus',
  'default_option' => 'Select a menu'
),
```

```php
// added query_args support for custom query
array(
  'id'         => 'unique_select_10_1',
  'type'       => 'select',
  'title'      => 'Select with Menus',
  'options'    => 'menus',
  'query_args' => array(
    'order' => 'DESC'
  ),
  'default_option' => 'Select a menu'
),
```

**Comment by Ansif** [comment]
That's Awesome! :+1: Thanks bro! :smile:

**Comment by Codestar** [comment]
You're welcome, Cheers :+1: :wink:

**Pull request merged**
