### PR TITLE
rtl support and arabic translation

### PR DESCRIPTION
**Pull request by mhmoudsami**
1- added rtl supoort
2- added arabic translation

### CODE REVIEW

**Comment by Codestar** [comment]
Thank you :+1:

**Comment by Codestar** [comment]
And, I added more things for RTL support ;) I advise latest update.

**Comment by mhmoudsami** [comment]
thank u very much,
i saw your latest updates and you made it better than me ;) ,
this framework is the best WP framework i have ever used,
please excuse me for my bad english

**Comment by Codestar** [comment]
You're welcome, and thanks for your pretty comment :+1: my english is same too :smile:

**Comment by mhmoudsami** [comment]
:+1: .
by the way .
is it possible or Wysiwyg to work in the "group" field type ?

**Comment by Codestar** [comment]
hmm, it is not possible yet, btw we are discuss this subject here [Wysiwyg field in add more group](https://github.com/Codestar/codestar-framework/issues/30)

**Pull request merged**
