### PR TITLE
Added the Taxonomy metaboxes option

### PR DESCRIPTION
**Pull request by wowthemes**
Hi,

I have added the taxonomies metaboxes option. Please review and commit

Thanks

### CODE REVIEW

**Comment by Irfan-git** [comment]
I also think about this.

@Codestar can you please add this on next update of framework??

**Comment by Codestar** [comment]
Yes yes, i saw this, i will merge this asap :wink: and @wowthemes thanks for contribute :+1:

**Comment by Codestar** [comment]
Hi,

I am working on this request now.  Thanks for your contribute. But, i need to change a lot of things for fully support Taxonomy framework. For eg. CSS Style support, sanitize, validate, rtl language, multilang supports etc.

I have a beta version for this request. can you test and tell me what you think ? You can download example theme [codestar-theme.zip](https://dl.dropboxusercontent.com/u/130410647/codestar-theme.zip) active it on local and take a look Posts &rarr; Categories / Tags

**Comment by Codevz** [comment]
Hi @Codestar 

Thanks for this update, I did test and working fine :smile: :+1:

**Comment by Codestar** [comment]
@Codevz Thanks for testing. I think I am ready for release it after your message :+1: :smile:

**Comment by Codestar** [comment]
This request added since v1.0.1 :+1:

**Comment by Slobork** [comment]
Maybe it's worth to note that this won't work on WP's installations prior to version 4.4.

**Comment by Codestar** [comment]
@Slobork Yes, you are right. Because add_term_meta, get_term_meta, delete_term_meta, update_term_mete added since version 4.4

https://make.wordpress.org/core/2015/10/23/4-4-taxonomy-roundup/

**Comment by Slobork** [comment]
@Codestar  Yeap, I'm aware that terms meta are introduced in 4.4. 
What I'm saying  is that making a note regarding this somewhere, e.g. in the taxonomy config file or in documentation would be a good thing.

Personally, I would much more like if you focus on other thinks than providing a fallback for this option. I've see a lot of exciting features you've noted for the next release. We are close to the WordPress 4.5 release and that means already 2 versions will support this feature. I doubt users will be installing the newest CS framework with new features on the old WP installations... or upgrading the framework without upgrading the WP. Even if they do that, the framework won't break anything, they just won't have the metaboxes for taxonomies (which is already the case if they are using the CS 1.0.0 ). 

I think that it just has to be stated that the metaboxes for taxonomies requires at least WP 4.4.

Cheers!

**Comment by Codestar** [comment]
@Slobork Yes you are right totally. i will add a fallback for this functions for add/edit. for eg.

```php
// before version 4.4
get_option( 'cs_term_meta_'. $taxonomy_name, 'value' );
update_option( 'cs_term_meta_'. $taxonomy_name, 'value' );
```

Ok bro, i noted this ;)

**Comment by Codestar** [comment]
@Slobork Now i am thinking to add this.

https://gist.github.com/Codestar/0f2b362885417aa37f168a22bfdbb36c

**Comment by Codestar** [comment]
@Slobork yes you are right totally, we need to add a fallback for this. Ok, today i added a fallback on developer branch. You can download it from https://github.com/Codestar/codestar-framework/archive/dev.zip extract and move files on themes folder. and test taxonomy framework in older WP and tell us the result.

**Comment by Slobork** [comment]
@Codestar Well, you go out of my expectations. Just checked it on WP 4.3. Everything is working very well. Great man!

**Comment by Codestar** [comment]
@Slobork thanks for check and report idea :+1: it will come in next update 1.0.2 :wink:

**Pull request closed without merging**
